### ISSUE TITLE
Request for pocket-cdg

### ISSUE THREAD

**Issue by zach-morris** [kodi-game/kodi-game-scripting#62]
https://github.com/libretro/libretro-pocketcdg

Request from the [forums](https://forum.kodi.tv/showthread.php?tid=330416&pid=2838424#pid2838424).  It might be a round about way of adding karaoke support back into Kodi.

**Comment by nonobio** [comment]
Hello zach-morris,

Why this issue is closed ?Is pocket-cdg now include ?

**Comment by zach-morris** [comment]
No, but this request is covered by [63](https://github.com/kodi-game/kodi-game-scripting/issues/63), which covers all the not yet included cores

**Comment by nonobio** [comment]
Ok, i suscribed to it. By the way : congralutations and thanls for your work :)

**Comment by zach-morris** [comment]
If you want an alternative (for cores like pocketcdg), you can take a look here:
https://github.com/zach-morris/kodi_libretro_buildbot_game_addons

**Comment by nonobio** [comment]
Not sure to understand, it is an alternative respository to add libretro cores to Kodi which aren't listed in Kodi official repository ?

**Comment by zach-morris** [comment]
Yes, thats exactly what it is.  More info in the forum [here](https://forum.kodi.tv/showthread.php?tid=345619).
