### ISSUE TITLE
Missing Cores

### ISSUE THREAD

**Issue by zach-morris** [kodi-game/kodi-game-scripting#63]
Just comparing this script/kodi-game repo and the available cores in libretro.  Not saying these should all be added, but just documenting the ones that aren't yet included (not sure which are easily added and which wouldn't yet be supported like the ones that require HW acceleration):

atari800_libretro
blastem_libretro
cannonball_libretro
citra_libretro
craft_libretro
crocods_libretro
desmume_libretro
dosbox_svn_libretro
easyrpg_libretro
emux_chip8_libretro
emux_gb_libretro
emux_nes_libretro
emux_sms_libretro
fixgb_libretro
fixnes_libretro
freeintv_libretro
frodo_libretro
gearboy_libretro
gearsystem_libretro
gme_libretro
gpsp_libretro
higan_sfc_balanced_libretro
higan_sfc_libretro
kronos_libretro
mednafen_psx_hw_libretro
mess2015_libretro
mu_libretro
np2kai_libretro
oberon_libretro
openlara_libretro
opentyrian_libretro
pascal_pong_libretro
pocketcdg_libretro
ppsspp_libretro
px68k_libretro
redream_libretro
reminiscence_libretro
simcp_libretro
theodore_libretro
vice_x128_libretro
vice_xplus4_libretro
vice_xvic_libretro
xrick_libretro
yabasanshiro_libretro

**Comment by zach-morris** [comment]
Closing with #80

**Comment by garbear** [comment]
It looks like we lack the following add-ons now:

citra_libretro
dosbox_svn_libretro
easyrpg_libretro
emux_chip8_libretro
emux_gb_libretro
emux_nes_libretro
emux_sms_libretro
fixgb_libretro
fixnes_libretro
gearboy_libretro
gearsystem_libretro
gme_libretro
higan_sfc_balanced_libretro
higan_sfc_libretro
kronos_libretro
mednafen_psx_hw_libretro
mess2015_libretro
np2kai_libretro
oberon_libretro
opentyrian_libretro
pascal_pong_libretro
redream_libretro
simcp_libretro
vice_x128_libretro
vice_xplus4_libretro
vice_xvic_libretro
xrick_libretro
yabasanshiro_libretro

should all of these be added?

**Comment by zach-morris** [comment]
The more the better in my opinion :-)
I see the work you've done with CI/CD so I figured more seamless integration for all the libretro cores was in work.  I might start having some time for this hobby near the of the month, and if it's not already tackled by then, I'll use some of your other examples and try to create some of these.
